-- 20260715001_add_dr_tasks.up.sql
--
-- DR portal — Tasks (Jira-style kanban board at /dr/tasks). Two tables:
--   dr_tasks         — one card. task_number is a GENERATED IDENTITY used only
--                      for the human display key "DR-<n>" (computed in the
--                      handler, never stored); numbers are never reused, so an
--                      archived task keeps its key forever. status is the board
--                      column; position is a fractional NUMERIC ordering WITHIN
--                      a column (new/moved cards get midpoints or ±1024 gaps;
--                      when midpoint gaps collapse below 1e-6 the move handler
--                      rebalances the whole column to 1024, 2048, 3072, … inside
--                      the same transaction). description is the SAME restricted
--                      dr-blocks/v1 message subset used by feedback messages
--                      (paragraph/code/list/blockquote, validated by
--                      validateDrMessageJSON) — NULL means no description.
--                      assignee_email must be on the DR_ALLOWED_EMAILS allowlist
--                      (handler-enforced; there is no users table) and NULL
--                      means unassigned. labels are normalized lowercase slugs
--                      (handler-enforced: [a-z0-9-], 1–30 chars, max 10).
--                      archived_at is a soft delete: archived tasks leave the
--                      board but stay retrievable by id (and listable with
--                      ?includeArchived=1). Authorship (created_by_*) comes from
--                      the verified Firebase claims in the API layer, never from
--                      request bodies.
--   dr_task_activity — append-only audit feed, ONE row per changed field
--                      (a PATCH touching title + priority writes two rows).
--                      action is the verb ('created'/'updated'/'moved'/
--                      'assigned'/'archived'/'restored'); field names the
--                      changed attribute for updated/moved/assigned rows and is
--                      NULL for created/archived/restored. old_value/new_value
--                      are human-readable renderings ('' for empty; description
--                      changes use '(updated)'-style markers, never block JSON).
--                      seq is a monotonic identity so ties on created_at order
--                      deterministically: ORDER BY (created_at, seq).
-- No S3 usage anywhere in this feature. Hard delete of a task CASCADEs its
-- activity rows (operator-only; the API only soft-deletes via archived_at).

BEGIN;

CREATE TABLE dr_tasks (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    task_number   bigint GENERATED ALWAYS AS IDENTITY UNIQUE,  -- display key "DR-<n>"; never reused
    title         text NOT NULL,                               -- 1..250 chars, handler-enforced
    description   jsonb,                                       -- restricted dr-blocks/v1 subset; NULL = no description
    status        text NOT NULL DEFAULT 'backlog'
                  CHECK (status IN ('backlog','todo','in_progress','in_review','done')),
    type          text NOT NULL DEFAULT 'task'
                  CHECK (type IN ('task','bug','feature','improvement')),
    priority      text NOT NULL DEFAULT 'medium'
                  CHECK (priority IN ('lowest','low','medium','high','highest')),
    assignee_email  text,                                      -- lowercased; NULL = unassigned; must be in DR_ALLOWED_EMAILS
    created_by_uid    text NOT NULL,                           -- reporter, from verified claims
    created_by_email  text NOT NULL,                           -- lowercased
    labels        text[] NOT NULL DEFAULT '{}',                -- normalized lowercase slugs
    due_date      date,
    position      numeric(20,10) NOT NULL,                     -- fractional ordering WITHIN a status column
    archived_at   timestamptz,                                 -- soft delete; NULL = active
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dr_tasks_board_idx    ON dr_tasks(status, position) WHERE archived_at IS NULL;
CREATE INDEX dr_tasks_archived_idx ON dr_tasks(archived_at DESC) WHERE archived_at IS NOT NULL;

CREATE TABLE dr_task_activity (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id      uuid NOT NULL REFERENCES dr_tasks(id) ON DELETE CASCADE,
    seq          bigint GENERATED BY DEFAULT AS IDENTITY,      -- deterministic ordering: (created_at, seq)
    actor_uid    text NOT NULL,
    actor_email  text NOT NULL,                                -- lowercased
    action       text NOT NULL
                 CHECK (action IN ('created','updated','moved','assigned','archived','restored')),
    field        text,          -- e.g. 'title','description','status','type','priority','assignee','labels','dueDate'; NULL for created/archived/restored
    old_value    text,          -- human-readable rendering ('' for empty)
    new_value    text,
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dr_task_activity_task_idx ON dr_task_activity(task_id, created_at, seq);

COMMIT;
