-- 20260707001_add_dr_chatlab.up.sql
--
-- DR portal — AI Chat Test Lab (ChatGPT-style chat at /dr/demos/chat-lab,
-- backed by OpenRouter through the Go API). Three tables:
--   dr_chat_sessions    — one chat. Sessions are SHARED between the two portal
--                         users (like feedback channels): any allowlisted user
--                         can read/continue any session; rename + delete are
--                         creator-only (enforced in the handler with a
--                         case-insensitive email compare). title_source tracks
--                         how the title was set ('default' → auto-titling still
--                         pending; 'derived' → truncated first message;
--                         'generated' → cheap-LLM title; 'manual' → renamed by
--                         the creator, never overwritten by auto-titling).
--                         last_model / last_reasoning_effort remember the
--                         composer selection so reopening a chat preselects it.
--                         updated_at is bumped on every message (recency sort).
--   dr_chat_messages    — one turn per row. role 'user' (author from the
--                         verified Firebase claims) or 'assistant' (author
--                         NULL; model/usage/cost captured from OpenRouter).
--                         Assistant content is plain markdown TEXT (model
--                         output, rendered client-side) — NOT dr-blocks.
--                         status records how the turn ended: 'complete',
--                         'interrupted' (client stopped/disconnected mid-
--                         stream; partial content persisted) or 'error'
--                         (upstream failure; safe summary in error_message).
--                         seq is a global monotonic identity so ties on
--                         created_at order deterministically: ORDER BY
--                         (created_at, seq).
--   dr_chat_attachments — image/file attachments on USER messages, uploaded via
--                         the standard MM S3 handshake (presign -> client PUT ->
--                         complete). message_id is NULL while composing and is
--                         bound inside the send transaction; unbound rows older
--                         than 24h are reaped (see the DR chat-lab attachment
--                         reaper in cmd/api).
-- Session delete is a HARD delete (disposable test data): CASCADE removes
-- message/attachment rows and the handler best-effort deletes the session's S3
-- prefix. Authorship comes from the verified Firebase claims in the API layer,
-- never from request bodies.

BEGIN;

CREATE TABLE dr_chat_sessions (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title        text NOT NULL DEFAULT 'New Chat',
    title_source text NOT NULL DEFAULT 'default'
                 CHECK (title_source IN ('default', 'derived', 'generated', 'manual')),
    created_by_uid   text NOT NULL,
    created_by_email text NOT NULL,          -- lowercased
    last_model   text,                        -- last model used; preselect on reopen
    last_reasoning_effort text,               -- last effort used ('' = off)
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()  -- bumped on every message
);
CREATE INDEX dr_chat_sessions_recency_idx ON dr_chat_sessions(updated_at DESC, id);

CREATE TABLE dr_chat_messages (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  uuid NOT NULL REFERENCES dr_chat_sessions(id) ON DELETE CASCADE,
    seq         bigint GENERATED BY DEFAULT AS IDENTITY,  -- global monotonic; order by (created_at, seq)
    role        text NOT NULL CHECK (role IN ('user', 'assistant')),
    author_uid   text,   -- user messages only; NULL for assistant
    author_email text,   -- user messages only; NULL for assistant
    content     text NOT NULL,                -- plain text (user) / markdown (assistant)
    reasoning   text,                          -- assistant only: captured reasoning stream, may be NULL
    model       text,                          -- assistant: model that produced it; user: model requested
    reasoning_effort text,                     -- '' or 'minimal'|'low'|'medium'|'high'|'xhigh'
    status      text NOT NULL DEFAULT 'complete'
                CHECK (status IN ('complete', 'interrupted', 'error')),
    error_message    text,                     -- safe, user-facing error summary when status='error'
    prompt_tokens     integer,
    completion_tokens integer,
    reasoning_tokens  integer,
    total_cost_usd    numeric(12,6),           -- from OpenRouter usage accounting when available
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dr_chat_messages_session_idx ON dr_chat_messages(session_id, created_at, seq);

CREATE TABLE dr_chat_attachments (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id   uuid NOT NULL REFERENCES dr_chat_sessions(id) ON DELETE CASCADE,
    message_id   uuid REFERENCES dr_chat_messages(id) ON DELETE CASCADE,  -- NULL while composing
    author_uid   text NOT NULL,
    kind         text NOT NULL CHECK (kind IN ('image', 'file')),
    file_name    text NOT NULL,
    s3_key       text NOT NULL,
    content_type text NOT NULL,
    size_bytes   bigint NOT NULL,
    width        integer,
    height       integer,
    status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready')),
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dr_chat_attachments_message_idx ON dr_chat_attachments(message_id) WHERE message_id IS NOT NULL;
CREATE INDEX dr_chat_attachments_unbound_idx ON dr_chat_attachments(created_at) WHERE message_id IS NULL;

COMMIT;
